### ISSUE TITLE
Ignoring exception in slash command 'advise':

### ISSUE THREAD

**Issue by OswaldoInfante97** [skuqre/anise#1]
Hey there, i don't know if you are supporting this but i have a small issue, i managed to make the bot run and everything else works but the Advise Function, when i use it On discord it stays "Thinking" and on my console i get the following error:
```
Ignoring exception in slash command 'advise':
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 354, in invoke
    await call_param_func(self.callback, inter, self.cog, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 1083, in call_param_func
    return await maybe_coroutine(safe_call, function, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/disnake/utils.py", line 567, in maybe_coroutine
    return await value
  File "/home/user/Documents/anise/src/cogs/nikke.py", line 416, in advise
    name = self.charnames[(k if not (k in util.weirdfilter) else util.weirdfilter[k])]
KeyError: 'ludmilla_w'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1378, in process_application_commands
    await app_command.invoke(interaction)
  File "/home/user/.local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 722, in invoke
    await self.invoke_children(inter)
  File "/home/user/.local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 711, in invoke_children
    await subcmd.invoke(inter, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 363, in invoke
    raise CommandInvokeError(exc) from exc
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'ludmilla_w'

``` 
So far i haven't been able to fix it, any ide what could this be?

**Comment by skuqre** [comment]
The Advise data really uses some weird naming cases, so there's a "weirdfilter" dictionary on `util.py` that sorts it out
I'd add a key with `ludmilla_w` and with the value of Ludmilla: Winter Owner's [prydwen.gg slug](https://www.prydwen.gg/nikke/characters/ludmilla-winter-owner) which is just `ludmilla-winter-owner` to it.

Expect to do this when they release nikkes that is just a variant of another nikke

**Comment by OswaldoInfante97** [comment]
Thank you That worked, I also had to add hongreyon_o too.

But now i seem to be facing a different issue:
```
Ignoring exception in on_button_click
Traceback (most recent call last):
File "/home/user/.local/lib/python3.10/site-packages/disnake/client.py", line 703, in _run_event
await coro(*args, **kwargs)
File "/home/user/Documentos/anise/src/cogs/extra.py", line 244, in on_button_click
upload = disnake.File(f'img\icon_bond_up.png', filename='bond.png')
File "/home/user/.local/lib/python3.10/site-packages/disnake/file.py", line 70, in init
self.fp = open(fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'img\icon_bond_up.png'

```
i have checked the folder permissions and the files are there is there any extra step i missed?
